import { Injectable, inject } from '@angular/core';

import { ApiClient } from './api.client';
import { ApiError } from './problem';

/**
 * The LGU's real business directory — `GET /staff/businesses` /
 * `GET /staff/businesses/:id`. Deliberately narrower than what the
 * Businesses page's list/detail UI shows: the server has no `subdomain`,
 * `userCount`, module-usage, analytics or activity-feed columns at all — its
 * own doc comment calls those "leftovers from a multi-tenant template" and
 * "generated by a seeded PRNG." Only the list/overview/applications tabs
 * this client's shape actually covers are real; the rest stay local/demo,
 * same as System Logs already honestly labels its own fabricated tabs.
 */

export interface StaffBusinessOwner {
  applicantId: string;
  name: string;
  email: string;
  mobileNumber: string | null;
}

export interface StaffBusinessRow {
  id: string;
  name: string;
  category: string;
  street: string;
  barangay: string;
  city: string;
  province: string;
  registrationNumber: string;
  dateRegistered: string;
  status: string;
  createdAt: string;
  owner: StaffBusinessOwner;
  applicationCount: number;
}

export interface StaffBusinessDetail extends StaffBusinessRow {
  applications: ReadonlyArray<{
    id: string;
    referenceNumber: string;
    permitType: string;
    applicationAction: string;
    lifecycleStatus: string;
    submittedAt: string | null;
  }>;
}

export type StaffBusinessListResult =
  | { readonly kind: 'ok'; readonly rows: readonly StaffBusinessRow[] }
  | { readonly kind: 'unavailable' }
  | { readonly kind: 'failed'; readonly message: string };

export type StaffBusinessDetailResult =
  | { readonly kind: 'ok'; readonly detail: StaffBusinessDetail }
  | { readonly kind: 'not-found' }
  | { readonly kind: 'unavailable' }
  | { readonly kind: 'failed'; readonly message: string };

/** `POST /staff/businesses` — registering a business at the counter, for an owner who may not yet have an account. */
export interface CreateBusinessInput {
  owner: {
    firstName: string;
    lastName: string;
    email: string;
    mobileNumber?: string;
  };
  business: {
    name: string;
    category: string;
    street: string;
    barangay: string;
    city: string;
    province: string;
    registrationNumber: string;
    /** `YYYY-MM-DD` */
    dateRegistered: string;
  };
}

export type CreateBusinessResult =
  | { readonly kind: 'done'; readonly businessId: string; readonly applicantId: string; readonly ownerNextStep: string | null }
  | { readonly kind: 'refused'; readonly message: string }
  | { readonly kind: 'unavailable' }
  | { readonly kind: 'failed'; readonly message: string };

/** `PATCH /staff/businesses/:id` — the owner-editable fields only; never the registration number/date or status. */
export interface UpdateBusinessInput {
  name: string;
  category: string;
  street: string;
  barangay: string;
  city: string;
  province: string;
}

export type UpdateBusinessResult =
  | { readonly kind: 'done'; readonly row: StaffBusinessRow }
  | { readonly kind: 'refused'; readonly message: string }
  | { readonly kind: 'unavailable' }
  | { readonly kind: 'failed'; readonly message: string };

export type SetBusinessStatusResult =
  | { readonly kind: 'done'; readonly row: StaffBusinessRow }
  | { readonly kind: 'refused'; readonly message: string }
  | { readonly kind: 'unavailable' }
  | { readonly kind: 'failed'; readonly message: string };

/** `POST /staff/businesses/announcements` — the Communication Center's real send. */
export type BroadcastAnnouncementResult =
  | { readonly kind: 'done'; readonly recipientCount: number }
  | { readonly kind: 'refused'; readonly message: string }
  | { readonly kind: 'unavailable' }
  | { readonly kind: 'failed'; readonly message: string };

@Injectable({ providedIn: 'root' })
export class StaffBusinessesApi {
  private readonly api = inject(ApiClient);

  async list(filters: { q?: string; category?: string; status?: string } = {}): Promise<StaffBusinessListResult> {
    try {
      const query: Record<string, string> = {};
      if (filters.q) query['q'] = filters.q;
      if (filters.category) query['category'] = filters.category;
      if (filters.status) query['status'] = filters.status;
      const result = await this.api.get<{ data: StaffBusinessRow[] }>('/staff/businesses', query);
      return { kind: 'ok', rows: result.data };
    } catch (error) {
      if (error instanceof ApiError) {
        if (error.status === 501) return { kind: 'unavailable' };
        return { kind: 'failed', message: error.message };
      }
      throw error;
    }
  }

  async detail(businessId: string): Promise<StaffBusinessDetailResult> {
    try {
      const detail = await this.api.get<StaffBusinessDetail>(`/staff/businesses/${encodeURIComponent(businessId)}`);
      return { kind: 'ok', detail };
    } catch (error) {
      if (error instanceof ApiError) {
        if (error.status === 404) return { kind: 'not-found' };
        if (error.status === 501) return { kind: 'unavailable' };
        return { kind: 'failed', message: error.message };
      }
      throw error;
    }
  }

  /**
   * The server creates the owner's account too, the same as
   * `StaffApplicationsApi.fileOnBehalf` does for a walk-in applicant — with
   * an unusable password; they set one later through account recovery.
   */
  async create(input: CreateBusinessInput): Promise<CreateBusinessResult> {
    try {
      const result = await this.api.post<{
        businessId: string;
        applicantId: string;
        ownerNextStep: string | null;
      }>('/staff/businesses', input, crypto.randomUUID());
      return { kind: 'done', ...result };
    } catch (error) {
      if (error instanceof ApiError) {
        if (error.status === 404 || error.status === 501) return { kind: 'unavailable' };
        // 409 = the Idempotency-Key collided with a different request; 422 =
        // the server's own registration service refused it (e.g. the owner's
        // email belongs to an LGU staff account).
        if (error.status === 409 || error.status === 422) {
          return { kind: 'refused', message: error.message };
        }
        return { kind: 'failed', message: error.message };
      }
      throw error;
    }
  }

  /** `PATCH /staff/businesses/:id` — corrects a business's own details on the LGU's behalf, any business (not gated to one the caller owns). */
  async update(businessId: string, input: UpdateBusinessInput): Promise<UpdateBusinessResult> {
    try {
      const row = await this.api.patch<StaffBusinessRow>(
        `/staff/businesses/${encodeURIComponent(businessId)}`, input,
      );
      return { kind: 'done', row };
    } catch (error) {
      if (error instanceof ApiError) {
        if (error.status === 404 || error.status === 501) return { kind: 'unavailable' };
        if (error.status === 422) return { kind: 'refused', message: error.message };
        return { kind: 'failed', message: error.message };
      }
      throw error;
    }
  }

  /**
   * `POST /staff/businesses/:id/deactivate` — marks Inactive. Never a hard
   * delete: `applications.business_id` is `on delete restrict`, so a
   * business with any application on file can never be deleted from the
   * database at all. Refused (422) while an application against it is
   * still in progress.
   */
  async deactivate(businessId: string): Promise<SetBusinessStatusResult> {
    return this.setStatus(businessId, 'deactivate');
  }

  /** Reverses `deactivate`. */
  async reactivate(businessId: string): Promise<SetBusinessStatusResult> {
    return this.setStatus(businessId, 'reactivate');
  }

  private async setStatus(businessId: string, action: 'deactivate' | 'reactivate'): Promise<SetBusinessStatusResult> {
    try {
      const row = await this.api.post<StaffBusinessRow>(
        `/staff/businesses/${encodeURIComponent(businessId)}/${action}`,
      );
      return { kind: 'done', row };
    } catch (error) {
      if (error instanceof ApiError) {
        if (error.status === 404 || error.status === 501) return { kind: 'unavailable' };
        if (error.status === 422) return { kind: 'refused', message: error.message };
        return { kind: 'failed', message: error.message };
      }
      throw error;
    }
  }

  /**
   * The Communication Center's "Broadcast Notice" — a real notification row
   * per business owner (`audience` scoping who), not a local-only UI state
   * change. See the server's own doc comment (staff-businesses.controller.ts)
   * for why this reuses the existing `account-update` notification type.
   */
  async broadcastAnnouncement(message: string, audience: 'all' | 'active'): Promise<BroadcastAnnouncementResult> {
    try {
      const result = await this.api.post<{ recipientCount: number }>(
        '/staff/businesses/announcements', { message, audience },
      );
      return { kind: 'done', recipientCount: result.recipientCount };
    } catch (error) {
      if (error instanceof ApiError) {
        if (error.status === 404 || error.status === 501) return { kind: 'unavailable' };
        if (error.status === 422 || error.status === 400) return { kind: 'refused', message: error.message };
        return { kind: 'failed', message: error.message };
      }
      throw error;
    }
  }
}
