import { Injectable, inject } from '@angular/core';

import { ApiClient } from './api.client';
import { ApiError } from './problem';

/**
 * The LGU's real business directory — `GET /staff/businesses` /
 * `GET /staff/businesses/:id`. Deliberately narrower than what the
 * Businesses page's list/detail UI shows: the server has no `subdomain`,
 * `userCount`, module-usage, analytics or activity-feed columns at all — its
 * own doc comment calls those "leftovers from a multi-tenant template" and
 * "generated by a seeded PRNG." Only the list/overview/applications tabs
 * this client's shape actually covers are real; the rest stay local/demo,
 * same as System Logs already honestly labels its own fabricated tabs.
 */

export interface StaffBusinessOwner {
  applicantId: string;
  name: string;
  email: string;
  mobileNumber: string | null;
}

export interface StaffBusinessRow {
  id: string;
  name: string;
  category: string;
  street: string;
  barangay: string;
  city: string;
  province: string;
  registrationNumber: string;
  dateRegistered: string;
  status: string;
  createdAt: string;
  owner: StaffBusinessOwner;
  applicationCount: number;
}

export interface StaffBusinessDetail extends StaffBusinessRow {
  applications: ReadonlyArray<{
    id: string;
    referenceNumber: string;
    permitType: string;
    applicationAction: string;
    lifecycleStatus: string;
    submittedAt: string | null;
  }>;
}

export type StaffBusinessListResult =
  | { readonly kind: 'ok'; readonly rows: readonly StaffBusinessRow[] }
  | { readonly kind: 'unavailable' }
  | { readonly kind: 'failed'; readonly message: string };

export type StaffBusinessDetailResult =
  | { readonly kind: 'ok'; readonly detail: StaffBusinessDetail }
  | { readonly kind: 'not-found' }
  | { readonly kind: 'unavailable' }
  | { readonly kind: 'failed'; readonly message: string };

@Injectable({ providedIn: 'root' })
export class StaffBusinessesApi {
  private readonly api = inject(ApiClient);

  async list(filters: { q?: string; category?: string; status?: string } = {}): Promise<StaffBusinessListResult> {
    try {
      const query: Record<string, string> = {};
      if (filters.q) query['q'] = filters.q;
      if (filters.category) query['category'] = filters.category;
      if (filters.status) query['status'] = filters.status;
      const result = await this.api.get<{ data: StaffBusinessRow[] }>('/staff/businesses', query);
      return { kind: 'ok', rows: result.data };
    } catch (error) {
      if (error instanceof ApiError) {
        if (error.status === 501) return { kind: 'unavailable' };
        return { kind: 'failed', message: error.message };
      }
      throw error;
    }
  }

  async detail(businessId: string): Promise<StaffBusinessDetailResult> {
    try {
      const detail = await this.api.get<StaffBusinessDetail>(`/staff/businesses/${encodeURIComponent(businessId)}`);
      return { kind: 'ok', detail };
    } catch (error) {
      if (error instanceof ApiError) {
        if (error.status === 404) return { kind: 'not-found' };
        if (error.status === 501) return { kind: 'unavailable' };
        return { kind: 'failed', message: error.message };
      }
      throw error;
    }
  }
}
